// ********RoostGPT********
/*
Test generated by RoostGPT for test gitTest1234 using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=ArticleStore_GetCommentByID_7ecaa81f20
ROOST_METHOD_SIG_HASH=ArticleStore_GetCommentByID_f6f8a51973

FUNCTION_DEF=func (s *ArticleStore) GetCommentByID(id uint) (*model.Comment, error) // GetCommentByID finds an comment from id

Scenario 1: Successful retrieval of a comment by ID

Details:
    Description: This test is meant to check if the function can successfully retrieve a comment by its ID from the database.
Execution:
    Arrange: Mock the database to return a specific comment when queried with a specific ID.
    Act: Invoke the GetCommentByID function with the ID of the mocked comment.
    Assert: Use Go testing facilities to verify that the returned comment matches the mocked comment.
Validation:
    The assertion checks that the function correctly retrieves and returns the comment from the database. This test is important to ensure that the function can successfully perform its primary task of retrieving a comment by its ID.

Scenario 2: Attempt to retrieve a non-existent comment by ID

Details:
    Description: This test is meant to check how the function handles the scenario where it is asked to retrieve a comment that does not exist in the database.
Execution:
    Arrange: Mock the database to return an error when queried with a non-existent ID.
    Act: Invoke the GetCommentByID function with a non-existent ID.
    Assert: Use Go testing facilities to verify that the function returns an error.
Validation:
    The assertion checks that the function correctly handles the error from the database and propagates it to the caller. This test is important to ensure that the function can gracefully handle errors and edge cases.

Scenario 3: Database error during retrieval of a comment by ID

Details:
    Description: This test is meant to check how the function handles a database error that occurs during the retrieval of a comment.
Execution:
    Arrange: Mock the database to return a database error when queried with a specific ID.
    Act: Invoke the GetCommentByID function with the ID that triggers the database error.
    Assert: Use Go testing facilities to verify that the function returns the database error.
Validation:
    The assertion checks that the function correctly handles the database error and propagates it to the caller. This test is important to ensure that the function can handle unexpected errors that may occur during database operations.
*/

// ********RoostGPT********

package store

import (
	"errors"
	"testing"

	"github.com/DATA-DOG/go-sqlmock"
	"github.com/jinzhu/gorm"
	"github.com/raahii/golang-grpc-realworld-example/model"
)

func TestArticleStoreGetCommentById(t *testing.T) {

	testCases := []struct {
		name          string
		id            uint
		mockBehaviour func(mock sqlmock.Sqlmock, id uint)
		expected      *model.Comment
		expectedErr   error
	}{
		{
			name: "Successful retrieval of a comment by ID",
			id:   1,
			mockBehaviour: func(mock sqlmock.Sqlmock, id uint) {
				rows := sqlmock.NewRows([]string{"id", "body"}).
					AddRow(id, "Test Comment")
				mock.ExpectQuery("^SELECT (.+) FROM \"comments\" WHERE (.+)").
					WithArgs(id).
					WillReturnRows(rows)
			},
			expected: &model.Comment{
				Model: gorm.Model{ID: 1},
				Body:  "Test Comment",
			},
			expectedErr: nil,
		},
		{
			name: "Attempt to retrieve a non-existent comment by ID",
			id:   2,
			mockBehaviour: func(mock sqlmock.Sqlmock, id uint) {
				mock.ExpectQuery("^SELECT (.+) FROM \"comments\" WHERE (.+)").
					WithArgs(id).
					WillReturnError(gorm.ErrRecordNotFound)
			},
			expected:    nil,
			expectedErr: gorm.ErrRecordNotFound,
		},
		{
			name: "Database error during retrieval of a comment by ID",
			id:   3,
			mockBehaviour: func(mock sqlmock.Sqlmock, id uint) {
				mock.ExpectQuery("^SELECT (.+) FROM \"comments\" WHERE (.+)").
					WithArgs(id).
					WillReturnError(errors.New("database error"))
			},
			expected:    nil,
			expectedErr: errors.New("database error"),
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			defer func() {
				if r := recover(); r != nil {
					t.Logf("Panic encountered so failing test. %v", r)
					t.Fail()
				}
			}()

			db, mock, err := sqlmock.New()
			if err != nil {
				t.Fatalf("an error '%s' was not expected when opening a stub database connection", err)
			}
			defer db.Close()

			gormDB, err := gorm.Open("postgres", db)
			if err != nil {
				t.Fatalf("an error '%s' was not expected when opening gorm database", err)
			}

			tc.mockBehaviour(mock, tc.id)

			store := &ArticleStore{
				db: gormDB,
			}

			comment, err := store.GetCommentByID(tc.id)

			if tc.expectedErr != nil {
				if err == nil {
					t.Errorf("expected error, got nil")
				} else if err.Error() != tc.expectedErr.Error() {
					t.Errorf("expected error '%s', got '%s'", tc.expectedErr, err)
				}
			} else {
				if err != nil {
					t.Errorf("expected no error, got '%s'", err)
				} else if comment.ID != tc.expected.ID || comment.Body != tc.expected.Body {
					t.Errorf("expected comment '%v', got '%v'", tc.expected, comment)
				}
			}
		})
	}
}
