// ********RoostGPT********
/*
Test generated by RoostGPT for test gitTest1234 using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=ArticleStore_GetComments_d7c78dda64
ROOST_METHOD_SIG_HASH=ArticleStore_GetComments_af08ddd59e

FUNCTION_DEF=func (s *ArticleStore) GetComments(m *model.Article) ([ // GetComments gets coments of the article
]model.Comment, error)
Scenario 1: Successful retrieval of comments for a given article

Details:
    Description: This test is meant to check if the function correctly retrieves all comments associated with a given article.
Execution:
    Arrange: Create a mock database with a predefined set of comments associated with a specific article. Instantiate an ArticleStore with the mock database.
    Act: Invoke the GetComments function with the article that has associated comments.
    Assert: Verify that the returned comments match the predefined set and that no error is returned.
Validation:
    The assertion checks that the function correctly retrieves all comments associated with a given article. This is crucial for the application's functionality as it allows users to view discussions related to an article.

Scenario 2: Retrieval of comments for an article with no comments

Details:
    Description: This test is meant to check if the function correctly handles the case where an article has no associated comments.
Execution:
    Arrange: Create a mock database with an article that has no associated comments. Instantiate an ArticleStore with the mock database.
    Act: Invoke the GetComments function with the article that has no comments.
    Assert: Verify that the returned slice of comments is empty and that no error is returned.
Validation:
    The assertion checks that the function correctly handles the case where an article has no comments. This is important for the application's robustness as it ensures that the function can handle all possible inputs.

Scenario 3: Retrieval of comments for a non-existent article

Details:
    Description: This test is meant to check if the function correctly handles the case where the given article does not exist in the database.
Execution:
    Arrange: Create a mock database without any articles. Instantiate an ArticleStore with the mock database.
    Act: Invoke the GetComments function with an article that does not exist in the database.
    Assert: Verify that an error is returned.
Validation:
    The assertion checks that the function correctly returns an error when the given article does not exist in the database. This is important for the application's robustness as it ensures that the function can handle invalid inputs.

Scenario 4: Database error during retrieval of comments

Details:
    Description: This test is meant to check if the function correctly handles a database error that occurs during the retrieval of comments.
Execution:
    Arrange: Create a mock database that returns an error when a query is executed. Instantiate an ArticleStore with the mock database.
    Act: Invoke the GetComments function with any article.
    Assert: Verify that an error is returned.
Validation:
    The assertion checks that the function correctly returns an error when a database error occurs. This is important for the application's robustness as it ensures that the function can handle unexpected errors during execution.
*/

// ********RoostGPT********

package store

import (
	"errors"
	"runtime/debug"
	"testing"

	"github.com/DATA-DOG/go-sqlmock"
	"github.com/jinzhu/gorm"
	"github.com/raahii/golang-grpc-realworld-example/model"
)

func TestArticleStoreGetComments(t *testing.T) {

	testCases := []struct {
		name     string
		article  *model.Article
		mockFunc func(mock sqlmock.Sqlmock, article *model.Article)
		wantErr  bool
	}{
		{
			name: "Successful retrieval of comments for a given article",
			article: &model.Article{
				Model: gorm.Model{ID: 1},
			},
			mockFunc: func(mock sqlmock.Sqlmock, article *model.Article) {
				rows := sqlmock.NewRows([]string{"ID", "Body", "ArticleID", "AuthorID"}).
					AddRow(1, "Test comment", article.Model.ID, 1).
					AddRow(2, "Another test comment", article.Model.ID, 1)
				mock.ExpectQuery("^SELECT (.+) FROM \"comments\"*").WillReturnRows(rows)
			},
			wantErr: false,
		},
		{
			name: "Retrieval of comments for an article with no comments",
			article: &model.Article{
				Model: gorm.Model{ID: 2},
			},
			mockFunc: func(mock sqlmock.Sqlmock, article *model.Article) {
				rows := sqlmock.NewRows([]string{"ID", "Body", "ArticleID", "AuthorID"})
				mock.ExpectQuery("^SELECT (.+) FROM \"comments\"*").WillReturnRows(rows)
			},
			wantErr: false,
		},
		{
			name: "Retrieval of comments for a non-existent article",
			article: &model.Article{
				Model: gorm.Model{ID: 3},
			},
			mockFunc: func(mock sqlmock.Sqlmock, article *model.Article) {
				mock.ExpectQuery("^SELECT (.+) FROM \"comments\"*").WillReturnError(gorm.ErrRecordNotFound)
			},
			wantErr: true,
		},
		{
			name: "Database error during retrieval of comments",
			article: &model.Article{
				Model: gorm.Model{ID: 4},
			},
			mockFunc: func(mock sqlmock.Sqlmock, article *model.Article) {
				mock.ExpectQuery("^SELECT (.+) FROM \"comments\"*").WillReturnError(errors.New("database error"))
			},
			wantErr: true,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			defer func() {
				if r := recover(); r != nil {
					t.Logf("Panic encountered so failing test. %v\n%s", r, string(debug.Stack()))
					t.Fail()
				}
			}()

			db, mock, err := sqlmock.New()
			if err != nil {
				t.Fatalf("Failed to create sqlmock: %v", err)
			}
			defer db.Close()

			gormDB, err := gorm.Open("postgres", db)
			if err != nil {
				t.Fatalf("Failed to open gorm DB: %v", err)
			}

			tc.mockFunc(mock, tc.article)

			store := &ArticleStore{
				db: gormDB,
			}

			_, err = store.GetComments(tc.article)

			if tc.wantErr {
				if err == nil {
					t.Errorf("Expected error, got nil")
				}
			} else {
				if err != nil {
					t.Errorf("Unexpected error: %v", err)
				}
			}
		})
	}
}
