// ********RoostGPT********
/*
Test generated by RoostGPT for test gitTest1234 using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=NewUserStore_fb599438e5
ROOST_METHOD_SIG_HASH=NewUserStore_c0075221af

FUNCTION_DEF=func NewUserStore(db *gorm.DB) *UserStore // NewUserStore returns a new UserStore

Scenario 1: Successful creation of a new UserStore

Details:
  Description: This test is meant to check if the NewUserStore function can successfully create a new UserStore instance when provided with a valid gorm.DB instance.
Execution:
  Arrange: Create a mock gorm.DB instance.
  Act: Invoke the NewUserStore function with the mock gorm.DB instance as the parameter.
  Assert: Use Go testing facilities to verify that the returned UserStore instance is not nil and its db field is the same as the mock gorm.DB instance.
Validation:
  The assertion checks if the returned UserStore instance is correctly initialized with the provided gorm.DB instance. This test is important to ensure that the NewUserStore function can correctly create new UserStore instances.

Scenario 2: Creation of a new UserStore with a nil gorm.DB instance

Details:
  Description: This test is meant to check if the NewUserStore function can handle a nil gorm.DB instance and still return a valid UserStore instance.
Execution:
  Arrange: No arrangement is needed as we are providing a nil parameter.
  Act: Invoke the NewUserStore function with nil as the parameter.
  Assert: Use Go testing facilities to verify that the returned UserStore instance is not nil and its db field is nil.
Validation:
  The assertion checks if the returned UserStore instance is correctly initialized with a nil db field. This test is important to ensure that the NewUserStore function can handle nil parameters and still return a valid UserStore instance.

Scenario 3: Multiple invocations of NewUserStore

Details:
  Description: This test is meant to check if multiple invocations of the NewUserStore function with the same gorm.DB instance return distinct UserStore instances.
Execution:
  Arrange: Create a mock gorm.DB instance.
  Act: Invoke the NewUserStore function twice with the same mock gorm.DB instance as the parameter.
  Assert: Use Go testing facilities to verify that the two returned UserStore instances are not the same.
Validation:
  The assertion checks if multiple invocations of the NewUserStore function return distinct UserStore instances even when provided with the same gorm.DB instance. This test is important to ensure that the NewUserStore function correctly creates new UserStore instances for each invocation.
*/

// ********RoostGPT********

package store

import (
	"runtime/debug"
	"testing"

	"github.com/DATA-DOG/go-sqlmock"
	"github.com/jinzhu/gorm"
	"github.com/stretchr/testify/assert"
)

func TestNewUserStore(t *testing.T) {

	testCases := []struct {
		name     string
		db       *gorm.DB
		expected *UserStore
	}{
		{
			name:     "Successful creation of a new UserStore",
			db:       new(gorm.DB),
			expected: &UserStore{db: new(gorm.DB)},
		},
		{
			name:     "Creation of a new UserStore with a nil gorm.DB instance",
			db:       nil,
			expected: &UserStore{db: nil},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {

			defer func() {
				if r := recover(); r != nil {
					t.Logf("Panic encountered so failing test. %v\n%s", r, string(debug.Stack()))
					t.Fail()
				}
			}()

			result := NewUserStore(tc.db)

			assert.Equal(t, tc.expected, result, "Expected and actual result should be the same")
		})
	}

	t.Run("Multiple invocations of NewUserStore", func(t *testing.T) {

		defer func() {
			if r := recover(); r != nil {
				t.Logf("Panic encountered so failing test. %v\n%s", r, string(debug.Stack()))
				t.Fail()
			}
		}()

		db, _, err := sqlmock.New()
		if err != nil {
			t.Fatalf("an error '%s' was not expected when opening a stub database connection", err)
		}
		gormDB, _ := gorm.Open("postgres", db)

		result1 := NewUserStore(gormDB)
		result2 := NewUserStore(gormDB)

		assert.NotEqual(t, result1, result2, "The two UserStore instances should not be the same")
	})
}
